Repository Numble3/Paws-Backend, pull requests merged in 2022-05, with the labels that each got.

#44 [docs] #40 Sign Swagger 추가
  src/main/java/com/numble/team3/sign/annotation/AccountWithdrawalSwagger.java
  src/main/java/com/numble/team3/sign/annotation/CreateAccessTokenSwagger.java
  src/main/java/com/numble/team3/sign/annotation/LogoutSwagger.java
  src/main/java/com/numble/team3/sign/annotation/SignInSwagger.java
  src/main/java/com/numble/team3/sign/annotation/SignUpSwagger.java
  src/main/java/com/numble/team3/sign/application/request/SignInDto.java
  src/main/java/com/numble/team3/sign/application/request/SignUpDto.java
  src/main/java/com/numble/team3/sign/application/response/TokenDto.java
  src/main/java/com/numble/team3/sign/controller/SignController.java
Labels: docs

#45 [feat] #39 Image 리사이즈 기능 추가
  build.gradle
  src/main/java/com/numble/team3/exception/image/ImageConvertFailureException.java
  src/main/java/com/numble/team3/exception/image/ImageResizeTypeUnSupportException.java
  src/main/java/com/numble/team3/exception/image/ImageTypeUnSupportException.java
  src/main/java/com/numble/team3/image/application/ApiGatewayImageService.java
  src/main/java/com/numble/team3/image/application/ImageService.java
  src/main/java/com/numble/team3/image/application/advice/ImageRestControllerAdvice.java
  src/main/java/com/numble/team3/image/application/request/CreateImageDto.java
  src/main/java/com/numble/team3/image/controller/ImageController.java
  src/main/resources/application.yml
Labels: feat

#50 [docs] #40 Image Swagger 추가
  src/main/java/com/numble/team3/image/annotation/ImageResizeSwagger.java
  src/main/java/com/numble/team3/image/application/request/CreateImageDto.java
  src/main/java/com/numble/team3/image/controller/ImageController.java
Labels: docs

#54 #51, #40 관심영상(Like) 관련 기능 추가
  src/main/java/com/numble/team3/common/entity/BaseTimeEntity.java
  src/main/java/com/numble/team3/config/QuerydslConfig.java
  src/main/java/com/numble/team3/config/WebConfig.java
  src/main/java/com/numble/team3/exception/like/LikeNotFoundException.java
  src/main/java/com/numble/team3/like/annotation/AddLikeSwagger.java
  src/main/java/com/numble/team3/like/annotation/DeleteLikeSwagger.java
  src/main/java/com/numble/team3/like/annotation/GetAllLikesSwagger.java
  src/main/java/com/numble/team3/like/annotation/GetLikesByCategorySwagger.java
  src/main/java/com/numble/team3/like/annotation/GetRankByDaySwagger.java
  src/main/java/com/numble/team3/like/application/LikeService.java
  src/main/java/com/numble/team3/like/application/RedisLikeService.java
  src/main/java/com/numble/team3/like/application/advice/LikeRestControllerAdvice.java
  src/main/java/com/numble/team3/like/application/response/GetAllLikeListDto.java
  src/main/java/com/numble/team3/like/application/response/GetLikeCategoryListLimitDto.java
  src/main/java/com/numble/team3/like/application/response/GetLikeDto.java
  src/main/java/com/numble/team3/like/application/response/GetLikeListDto.java
  src/main/java/com/numble/team3/like/application/response/GetLikeRankVideoDto.java
  src/main/java/com/numble/team3/like/application/response/GetVideoQuerydsl.java
  src/main/java/com/numble/team3/like/application/response/GetVideoRankDto.java
  src/main/java/com/numble/team3/like/controller/LikeController.java
  src/main/java/com/numble/team3/like/domain/Like.java
  src/main/java/com/numble/team3/like/infra/CustomJpaLikeRepository.java
  src/main/java/com/numble/team3/like/infra/CustomJpaLikeRepositoryImpl.java
  src/main/java/com/numble/team3/like/infra/JpaLikeRepository.java
  src/main/java/com/numble/team3/like/infra/LikeRedisUtils.java
  src/main/java/com/numble/team3/like/scheduler/LikeRankScheduler.java
  src/main/java/com/numble/team3/video/application/response/GetVideoDto.java
  src/main/resources/application.yml
Labels: feat, docs

#58 비디오 도메인 ffmpeg 의존성 제거 및 process api 패키지 변경
  src/main/java/com/numble/team3/comment/controller/CommentController.java
  src/main/java/com/numble/team3/comment/domain/Comment.java
  src/main/java/com/numble/team3/common/infra/S3Uploader.java
  src/main/java/com/numble/team3/converter/annotation/ImageResizeSwagger.java
  src/main/java/com/numble/team3/converter/application/ApiGatewayConvertService.java
  src/main/java/com/numble/team3/converter/application/ConvertService.java
  src/main/java/com/numble/team3/converter/application/advice/ConvertRestControllerAdvice.java
  src/main/java/com/numble/team3/converter/application/request/CreateImageDto.java
  src/main/java/com/numble/team3/converter/application/request/CreateVideoDto.java
  src/main/java/com/numble/team3/converter/application/response/GetConvertUrlDto.java
  src/main/java/com/numble/team3/converter/controller/ConvertController.java
  src/main/java/com/numble/team3/exception/convert/ImageConvertFailureException.java
  src/main/java/com/numble/team3/exception/convert/ImageResizeTypeUnSupportException.java
  src/main/java/com/numble/team3/exception/convert/ImageTypeUnSupportException.java
  src/main/java/com/numble/team3/exception/convert/VideoConvertFailureException.java
  src/main/java/com/numble/team3/exception/convert/VideoTypeUnSupportException.java
  src/main/java/com/numble/team3/image/application/ApiGatewayImageService.java
  src/main/java/com/numble/team3/image/application/ImageService.java
  src/main/java/com/numble/team3/image/controller/ImageController.java
  src/main/java/com/numble/team3/like/application/response/GetLikeRankVideoDto.java
  src/main/java/com/numble/team3/video/application/VideoService.java
  src/main/java/com/numble/team3/video/application/request/CreateOrUpdateVideoDto.java
  src/main/java/com/numble/team3/video/application/response/GetVideoDetailDto.java
  src/main/java/com/numble/team3/video/application/response/GetVideoDto.java
  src/main/java/com/numble/team3/video/controller/VideoController.java
  src/main/java/com/numble/team3/video/domain/Video.java
  src/main/java/com/numble/team3/video/domain/VideoUtils.java
  src/main/java/com/numble/team3/video/domain/enums/VideoType.java
  src/main/java/com/numble/team3/video/infra/VideoFfmpegUtils.java
  src/main/resources/application-ffmpeg.yml
  src/main/resources/application.yml
  src/test/java/com/numble/team3/Team3ApplicationTests.java
Labels: feat, refactor, rename

#59 [fix] #56, #58 git 충돌로 인해 누락된 로직 복구
  src/main/java/com/numble/team3/converter/application/advice/ConvertRestControllerAdvice.java
  src/main/java/com/numble/team3/converter/controller/ConvertController.java
Labels: fix

#60 [refactor] Redis 의존성 분리
  src/main/java/com/numble/team3/account/application/AccountService.java
  src/main/java/com/numble/team3/account/domain/AccountUtils.java
  src/main/java/com/numble/team3/account/infra/AccountRedisHelper.java
  src/main/java/com/numble/team3/account/infra/AccountRedisUtils.java
  src/main/java/com/numble/team3/config/SecurityConfig.java
  src/main/java/com/numble/team3/like/application/LikeService.java
  src/main/java/com/numble/team3/like/application/RedisLikeService.java
  src/main/java/com/numble/team3/like/domain/LikeUtils.java
  src/main/java/com/numble/team3/like/infra/LikeRedisHelper.java
  src/main/java/com/numble/team3/like/infra/LikeRedisUtils.java
  src/main/java/com/numble/team3/security/JwtAuthenticationFilter.java
  src/main/java/com/numble/team3/security/OAuth2SuccessHandler.java
  src/main/java/com/numble/team3/security/SecurityRedisUtils.java
  src/main/java/com/numble/team3/security/SecurityUtils.java
  src/main/java/com/numble/team3/sign/application/RedisSignService.java
  src/main/java/com/numble/team3/sign/application/SignService.java
  src/main/java/com/numble/team3/sign/domain/SignUtils.java
  src/main/java/com/numble/team3/sign/infra/RedisSignUtils.java
  src/main/java/com/numble/team3/sign/infra/SignRedisHelper.java
Labels: refactor

#62 [refactor] ApiGatewayConvertService 이미지 리사이즈 aws 의존성 분리
  src/main/java/com/numble/team3/converter/application/ApiGatewayConvertService.java
  src/main/java/com/numble/team3/converter/application/ConvertService.java
  src/main/java/com/numble/team3/converter/domain/ConvertImageUtils.java
  src/main/java/com/numble/team3/converter/infra/AwsConvertImageUtils.java
Labels: refactor

#66 [feat], [docs] 관리자 회원관리 관련 기능 추가
  src/main/java/com/numble/team3/account/application/AccountService.java
  src/main/java/com/numble/team3/account/domain/Account.java
  src/main/java/com/numble/team3/account/domain/AccountUtils.java
  src/main/java/com/numble/team3/account/infra/AccountRedisUtils.java
  src/main/java/com/numble/team3/account/infra/JpaAccountRepository.java
  src/main/java/com/numble/team3/admin/annotation/DeleteTokenSwagger.java
  src/main/java/com/numble/team3/admin/annotation/GetAccountSwagger.java
  src/main/java/com/numble/team3/admin/annotation/GetAccountsSwagger.java
  src/main/java/com/numble/team3/admin/annotation/WithdrawalSwagger.java
  src/main/java/com/numble/team3/admin/application/advice/AdminAccountRestControllerAdvice.java
  src/main/java/com/numble/team3/admin/application/response/GetAccountDetailDto.java
  src/main/java/com/numble/team3/admin/application/response/GetAccountListDto.java
  src/main/java/com/numble/team3/admin/application/response/GetAccountSimpleDto.java
  src/main/java/com/numble/team3/admin/controller/AdminAccountController.java
  src/main/java/com/numble/team3/sign/application/SignService.java
  src/main/java/com/numble/team3/sign/domain/SignUtils.java
  src/main/java/com/numble/team3/sign/infra/RedisSignUtils.java
Labels: feat, docs

#68 [feat], [docs] 프로필 관련 기능 추가
  src/main/java/com/numble/team3/account/annotation/GetMyAccountSwagger.java
  src/main/java/com/numble/team3/account/annotation/UpdateMyAccountSwagger.java
  src/main/java/com/numble/team3/account/annotation/WithdrawalAccountSwagger.java
  src/main/java/com/numble/team3/account/application/AccountService.java
  src/main/java/com/numble/team3/account/application/advice/AccountRestControllerAdvice.java
  src/main/java/com/numble/team3/account/application/request/UpdateMyAccountDto.java
  src/main/java/com/numble/team3/account/application/response/GetMyAccountDto.java
  src/main/java/com/numble/team3/account/controller/AccountController.java
  src/main/java/com/numble/team3/account/domain/Account.java
Labels: feat, docs

#69 [refactor] #63 Security, Swagger, Redis 설정 수정
  src/main/java/com/numble/team3/Team3Application.java
  src/main/java/com/numble/team3/common/advice/CommonRestControllerAdvice.java
  src/main/java/com/numble/team3/config/SecurityConfig.java
  src/main/java/com/numble/team3/config/SwaggerConfig.java
  src/main/java/com/numble/team3/like/annotation/AddLikeSwagger.java
  src/main/java/com/numble/team3/like/annotation/DeleteLikeSwagger.java
  src/main/java/com/numble/team3/like/annotation/GetAllLikesSwagger.java
  src/main/java/com/numble/team3/like/annotation/GetLikesByCategorySwagger.java
  src/main/java/com/numble/team3/sign/annotation/CreateAccessTokenSwagger.java
Labels: refactor

#70 [refactor] Account, Admin, Image, Sign 일부 수정
  src/main/java/com/numble/team3/account/annotation/UpdateMyAccountSwagger.java
  src/main/java/com/numble/team3/account/application/AccountService.java
  src/main/java/com/numble/team3/account/application/advice/AccountRestControllerAdvice.java
  src/main/java/com/numble/team3/account/controller/AccountController.java
  src/main/java/com/numble/team3/account/infra/JpaAccountRepository.java
  src/main/java/com/numble/team3/admin/controller/AdminAccountController.java
  src/main/java/com/numble/team3/converter/application/request/CreateImageDto.java
  src/main/java/com/numble/team3/sign/controller/SignController.java
Labels: refactor

#72 [test] 테스트 코드 추가
  src/test/java/com/numble/team3/account/application/AccountServiceTest.java
  src/test/java/com/numble/team3/account/application/request/UpdateMyAccountDtoTest.java
  src/test/java/com/numble/team3/account/controller/AccountControllerAdviceTest.java
  src/test/java/com/numble/team3/account/controller/AccountControllerTest.java
  src/test/java/com/numble/team3/admin/controller/AdminAccountControllerAdviceTest.java
  src/test/java/com/numble/team3/admin/controller/AdminAccountControllerTest.java
  src/test/java/com/numble/team3/converter/application/ConvertServiceImageTest.java
  src/test/java/com/numble/team3/converter/application/request/CreateImageDtoTest.java
  src/test/java/com/numble/team3/converter/controller/ConvertControllerAdviceTest.java
  src/test/java/com/numble/team3/converter/controller/ConvertControllerImageTest.java
  src/test/java/com/numble/team3/factory/UserInfoFactory.java
  src/test/java/com/numble/team3/factory/dto/AccountDtoFactory.java
  src/test/java/com/numble/team3/factory/dto/ImageDtoFactory.java
  src/test/java/com/numble/team3/factory/dto/LikeDtoFactory.java
  src/test/java/com/numble/team3/factory/dto/SignDtoFactory.java
  src/test/java/com/numble/team3/factory/entity/AccountEntityFactory.java
  src/test/java/com/numble/team3/factory/entity/LikeEntityFactory.java
  src/test/java/com/numble/team3/factory/entity/VideoEntityFactory.java
  src/test/java/com/numble/team3/jwt/JwtProviderTest.java
  src/test/java/com/numble/team3/jwt/TokenHelperTest.java
  src/test/java/com/numble/team3/like/application/LikeServiceTest.java
  src/test/java/com/numble/team3/like/controller/LikeControllerAdviceTest.java
  src/test/java/com/numble/team3/like/controller/LikeControllerTest.java
  src/test/java/com/numble/team3/sign/application/SignServiceTest.java
  src/test/java/com/numble/team3/sign/application/request/SignInDtoTest.java
  src/test/java/com/numble/team3/sign/application/request/SignUpDtoTest.java
  src/test/java/com/numble/team3/sign/controller/SignControllerAdviceTest.java
  src/test/java/com/numble/team3/sign/controller/SignControllerTest.java
Labels: test

#91 [refactor] #89 좋아요(관심영상) 추가, 조회 방식 변경
  src/main/java/com/numble/team3/like/application/LikeVideoService.java
  src/main/java/com/numble/team3/like/controller/LikeVideoController.java
  src/main/java/com/numble/team3/like/domain/LikeVideo.java
  src/main/java/com/numble/team3/like/infra/CustomJpaLikeVideoRepositoryImpl.java
  src/main/java/com/numble/team3/like/infra/JpaLikeVideoRepository.java
  src/test/java/com/numble/team3/factory/entity/LikeVideoEntityFactory.java
  src/test/java/com/numble/team3/like/application/LikeVideoServiceTest.java
  src/test/java/com/numble/team3/like/controller/LikeVideoVideoControllerTest.java
Labels: refactor

#93 [feat] #92 CORS 설정 추가
  src/main/java/com/numble/team3/config/CorsConfig.java
Labels: feat

#94 [refactor] AccountService.updateAccount 로직 수정
  src/main/java/com/numble/team3/account/application/AccountService.java
Labels: refactor

#95 [refactor] CorsConfig 수정
  src/main/java/com/numble/team3/config/CorsConfig.java
Labels: refactor

#98 [docs] Swagger Response 예시 수정
  src/main/java/com/numble/team3/account/annotation/GetMyAccountSwagger.java
  src/main/java/com/numble/team3/admin/annotation/GetAccountSwagger.java
  src/main/java/com/numble/team3/admin/annotation/GetAccountsSwagger.java
  src/main/java/com/numble/team3/converter/annotation/ImageResizeSwagger.java
  src/main/java/com/numble/team3/like/annotation/GetAllLikeVideosSwagger.java
  src/main/java/com/numble/team3/like/annotation/GetLikeVideosByCategorySwagger.java
  src/main/java/com/numble/team3/like/annotation/GetVideoRankByDayLikeSwagger.java
Labels: docs

#100 [feat] #90 회원 정보 상세 조회, 업로드 영상 조회 기능 추가
  src/main/java/com/numble/team3/account/annotation/GetMyAccountDetailSwagger.java
  src/main/java/com/numble/team3/account/annotation/GetMyVideosSwagger.java
  src/main/java/com/numble/team3/account/application/AccountService.java
  src/main/java/com/numble/team3/account/application/response/GetMyAccountDetailDto.java
  src/main/java/com/numble/team3/account/application/response/GetMySimpleVideoDto.java
  src/main/java/com/numble/team3/account/application/response/GetMyVideosDto.java
  src/main/java/com/numble/team3/account/controller/AccountController.java
  src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepository.java
  src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java
  src/main/java/com/numble/team3/video/infra/JpaVideoRepository.java
  src/main/resources/application.yml
  src/test/java/com/numble/team3/account/application/AccountServiceTest.java
Labels: feat

#102 [refactor] CORS 설정 변경
  src/main/java/com/numble/team3/config/CorsConfig.java
  src/main/java/com/numble/team3/config/SecurityConfig.java
Labels: refactor

#103 [refactor] CORS 설정 변경
  src/main/java/com/numble/team3/config/SecurityConfig.java
Labels: refactor

#108 [refactor] Cookie 생성 방식 변경
  src/main/java/com/numble/team3/sign/controller/SignController.java
Labels: refactor

#111 [refactor] Cookie 생성 옵션 변경
  src/main/java/com/numble/team3/sign/controller/SignController.java
Labels: refactor

#114 [refactor] Cookie 생성 옵션 변경
  src/main/java/com/numble/team3/sign/controller/SignController.java
Labels: refactor

#118 [refactor] Cookie 생성 옵션 변경
  src/main/java/com/numble/team3/sign/controller/SignController.java
  src/test/java/com/numble/team3/sign/controller/SignControllerTest.java
Labels: refactor

#122 [refactor] #120 Sign 쿠키 관련 로직 삭제
  src/main/java/com/numble/team3/sign/annotation/CreateAccessTokenSwagger.java
  src/main/java/com/numble/team3/sign/controller/SignController.java
  src/test/java/com/numble/team3/sign/controller/SignControllerAdviceTest.java
  src/test/java/com/numble/team3/sign/controller/SignControllerTest.java
Labels: refactor

#125 [docs] Account 관련 Swagger 수정
  src/main/java/com/numble/team3/account/annotation/GetMyAccountDetailSwagger.java
  src/main/java/com/numble/team3/account/annotation/GetMyAccountSwagger.java
  src/main/java/com/numble/team3/account/annotation/GetMyVideosSwagger.java
  src/main/java/com/numble/team3/account/annotation/UpdateMyAccountSwagger.java
  src/main/java/com/numble/team3/account/annotation/WithdrawalAccountSwagger.java
Labels: docs

#131 [docs] Swagger 수정
  src/main/java/com/numble/team3/converter/annotation/ImageResizeSwagger.java
  src/main/java/com/numble/team3/sign/annotation/CreateAccessTokenSwagger.java
Labels: docs

#134 [feat] 관리자 회원 업로드 영상 목록 조회 기능 추가
  src/main/java/com/numble/team3/admin/annotation/GetAccountVideosSwagger.java
  src/main/java/com/numble/team3/admin/application/response/GetAccountVideosDto.java
  src/main/java/com/numble/team3/admin/application/response/GetSimpleAccountVideoDto.java
  src/main/java/com/numble/team3/admin/controller/AdminAccountController.java
  src/main/java/com/numble/team3/video/application/VideoService.java
  src/main/java/com/numble/team3/video/infra/JpaVideoRepository.java
Labels: feat

#135 [refactor] videos 페이지 수정
  src/main/java/com/numble/team3/admin/application/response/GetVideoListForAdminDto.java
Labels: refactor

#138 [refactor] GetVideoListForAdminDto 현재 페이지 방식 변경
  src/main/java/com/numble/team3/admin/application/response/GetVideoListForAdminDto.java
Labels: refactor

#141 [rename] Response Dto Field 이름 변경
  src/main/java/com/numble/team3/admin/annotation/GetAccountVideosSwagger.java
  src/main/java/com/numble/team3/admin/application/response/GetSimpleAccountVideoDto.java
Labels: rename

#142 [refactor] image resize log 추가
  src/main/java/com/numble/team3/converter/infra/AwsConvertImageUtils.java
Labels: refactor

#143 [refactor] GetVideoDetailForAdminDto Field 추가
  src/main/java/com/numble/team3/admin/application/response/GetVideoDetailForAdminDto.java
Labels: refactor

#144 [refactor] JpaAccountVideoRepositoryImpl cross join 해결
  src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java
Labels: refactor

#146 [refactor] getMyVideos 로직 수정
  src/main/java/com/numble/team3/account/application/AccountService.java
  src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java
Labels: refactor

#147 [refactor] RestControllerAdvice 수정
  src/main/java/com/numble/team3/common/advice/CommonRestControllerAdvice.java
Labels: refactor

#148 [refactor] RestControllerAdvice 수정
  src/main/java/com/numble/team3/common/advice/CommonRestControllerAdvice.java
Labels: refactor

#153 [refactor] Response VideoType 추가
  src/main/java/com/numble/team3/account/annotation/GetMyAccountDetailSwagger.java
  src/main/java/com/numble/team3/account/annotation/GetMyVideosSwagger.java
  src/main/java/com/numble/team3/account/application/response/GetMySimpleVideoDto.java
  src/main/java/com/numble/team3/video/application/response/GetVideoDto.java
  src/main/java/com/numble/team3/video/domain/enums/VideoType.java
  src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java
Labels: refactor

#154 [refactor] GetVideoDto 누락 수정
  src/main/java/com/numble/team3/video/application/response/GetVideoDto.java
Labels: refactor

#155 [refactor] GetVideoDto 누락 수정
  src/main/java/com/numble/team3/video/application/response/GetVideoDto.java
Labels: refactor

#156 [refactor] cors 설정 추가
  src/main/java/com/numble/team3/config/SecurityConfig.java
Labels: refactor

#157 [refactor] cors 설정 추가
  src/main/java/com/numble/team3/config/SecurityConfig.java
Labels: refactor

#158 [refactor] cors 설정 변경
  src/main/java/com/numble/team3/config/SecurityConfig.java
Labels: refactor

#159 [refactor] cors 설정 변경
  src/main/java/com/numble/team3/config/SecurityConfig.java
Labels: refactor

#160 [refactor] cors 설정 변경
  src/main/java/com/numble/team3/config/SecurityConfig.java
Labels: refactor

#161 [refactor] cors 설정 변경
  src/main/java/com/numble/team3/config/SecurityConfig.java
Labels: refactor

#163 [refactor] cors 설정 변경
  src/main/java/com/numble/team3/config/SecurityConfig.java
  src/main/java/com/numble/team3/like/application/LikeVideoService.java
Labels: refactor

#165 [refactor] getMyVideoDtos 로직 수정
  src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java
Labels: refactor

#166 [refactor] findAllByAccountIdWithAdmin 수정
  src/main/java/com/numble/team3/video/infra/JpaVideoRepository.java
Labels: refactor

#168 [refactor] findAllByAccountIdWithAdmin 수정 복구
  src/main/java/com/numble/team3/video/infra/JpaVideoRepository.java
Labels: refactor

#169 [refactor] findAllByAccountId 수정
  src/main/java/com/numble/team3/video/infra/JpaVideoRepository.java
Labels: refactor

#170 [refactor] cors origin 추가
  src/main/java/com/numble/team3/config/SecurityConfig.java
Labels: refactor

#171 [refactor] cors origin 추가
  src/main/java/com/numble/team3/config/SecurityConfig.java
Labels: refactor

#172 [refactor] cors front origin 추가
  src/main/java/com/numble/team3/config/SecurityConfig.java
Labels: refactor

#180 [refactor] getMyVideoDtos 수정
  src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java
Labels: refactor

#182 [refactor] getMyVideoDtos 수정
  src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java
Labels: refactor

#183 [refactor] GetLikeVideosByCategorySwagger 수정
  src/main/java/com/numble/team3/like/annotation/GetLikeVideosByCategorySwagger.java
Labels: refactor

#184 [refactor] GetLikeListDto 수정
  src/main/java/com/numble/team3/like/application/response/GetLikeListDto.java
Labels: refactor

#186 [refactor] getLikesByCategory 수정
  src/main/java/com/numble/team3/like/controller/LikeVideoController.java
  src/main/java/com/numble/team3/like/infra/CustomJpaLikeVideoRepositoryImpl.java
Labels: refactor

#190 [refactor] addLike 검증 로직 추가
  src/main/java/com/numble/team3/exception/like/LikeVideoAlreadyExistsException.java
  src/main/java/com/numble/team3/like/annotation/AddLikeVideoSwagger.java
  src/main/java/com/numble/team3/like/application/LikeVideoService.java
  src/main/java/com/numble/team3/like/application/advice/LikeVideoRestControllerAdvice.java
  src/main/java/com/numble/team3/like/infra/JpaLikeVideoRepository.java
Labels: refactor

#191 [refactor] existsLikeByVideoIdAndAccountId 수정
  src/main/java/com/numble/team3/like/infra/JpaLikeVideoRepository.java
Labels: refactor

#192 [refactor] addLike 검증 로직 수정
  src/main/java/com/numble/team3/like/application/LikeVideoService.java
  src/main/java/com/numble/team3/like/infra/JpaLikeVideoRepository.java
Labels: refactor

#200 [refactor] 좋아요 추가/삭제 시 로직 변경
  src/main/java/com/numble/team3/like/annotation/AddLikeVideoSwagger.java
  src/main/java/com/numble/team3/like/annotation/DeleteLikeVideoSwagger.java
  src/main/java/com/numble/team3/like/application/LikeVideoService.java
  src/main/java/com/numble/team3/like/controller/LikeVideoController.java
  src/main/java/com/numble/team3/video/domain/Video.java
  src/test/java/com/numble/team3/like/controller/LikeVideoVideoControllerTest.java
Labels: refactor

#201 [refactor] JpaLikeVideoRepository 수정
  src/main/java/com/numble/team3/like/infra/JpaLikeVideoRepository.java
Labels: refactor

#206 [refactor] ranking 관련 로직 수정
  src/main/java/com/numble/team3/admin/controller/AdminAccountController.java
  src/main/java/com/numble/team3/like/annotation/GetVideoRankByDayCategoryLikeSwagger.java
  src/main/java/com/numble/team3/like/annotation/GetVideoRankByDayLikeSwagger.java
  src/main/java/com/numble/team3/like/application/LikeVideoService.java
  src/main/java/com/numble/team3/like/application/response/GetLikeVideoRankDto.java
  src/main/java/com/numble/team3/like/application/response/GetVideoRankDto.java
  src/main/java/com/numble/team3/like/controller/LikeVideoController.java
  src/main/java/com/numble/team3/like/domain/LikeVideoUtils.java
  src/main/java/com/numble/team3/like/infra/CustomJpaLikeVideoRepository.java
  src/main/java/com/numble/team3/like/infra/CustomJpaLikeVideoRepositoryImpl.java
  src/main/java/com/numble/team3/like/infra/LikeVideoRedisHelper.java
  src/main/java/com/numble/team3/like/infra/LikeVideoRedisUtils.java
  src/test/java/com/numble/team3/factory/dto/LikeVideoDtoFactory.java
  src/test/java/com/numble/team3/like/application/LikeVideoServiceTest.java
  src/test/java/com/numble/team3/like/controller/LikeVideoVideoControllerTest.java
Labels: refactor
